USE ROLE SYSADMIN;

SELECT CURRENT_ROLE();

SELECT CURRENT_USER();

CREATE DATABASE IF NOT EXISTS chocolate_db;

CREATE WAREHOUSE dev_wh
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = "warehouse for development and analysis";


SHOW WAREHOUSES;
