CREATE DATABASE MY_CRUNCHBASE_DATA;

SHOW DATABASES;

USE DATABASE MY_CRUNCHBASE_DATA;

CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS  ANALYTICS;

CREATE TABLE STAGING.STG_COMPANIES (
    company_id INTEGER PRIMARY KEY,
    name VARCHAR(255),
    country VARCHAR(100),
    funding_total FLOAT,
    founded_year INTEGER

);

CREATE TABLE STAGING.STG_INVESTORS (
    investor_id INTEGER PRIMARY KEY,
    name VARCHAR(255),
    investment_amount FLOAT
);

SHOW DATABASES;

SHOW SCHEMAS;

SHOW TABLES;

SHOW VIEWS;

SELECT * FROM STAGING.STG_COMPANIES LIMIT 20;

SELECT * FROM STAGING."STG_COMPANIES" LIMIT 20;

DESC TABLE STAGING.STG_COMPANIES;
DESC TABLE STAGING.STG_INVESTORS;

INSERT INTO STAGING.STG_COMPANIES (company_id, name, country, funding_total, founded_year)
VALUES
(1, 'TechCorp', 'USA', 5000000.00, 2010),
(2, 'NordicStartup', 'SWE', 2500000.00, 2018),
(3, 'GreenEnergy', 'DNK', 7500000.00, 2015);

SELECT * FROM STAGING.STG_COMPANIES;

INSERT INTO STAGING.STG_INVESTORS (investor_id, name, investment_amount)
VALUES 
(1, 'Venture Capital AB', 2000000.00),
(2, 'Nordic Fund', 3000000.00),
(3, 'Angel Investor', 1000000.00);

SELECT * FROM STAGING.STG_INVESTORS;


DESC VIEW STAGING.STG_COMPANIES;

SELECT COUNT(*) AS number_rows FROM STAGING.STG_COMPANIES;

SELECT COUNT(DISTINCT name) AS number_unique_names
FROM STAGING.STG_COMPANIES LIMIT 5;



