SHOW WAREHOUSES;

CREATE WAREHOUSE talent_warehouse
WITH
WAREHOUSE_SIZE = 'X-small'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Talent warehouse created through a worksheet';

SHOW WAREHOUSES;
ALTER WAREHOUSE COMPUTE_WH
SET AUTO_SUSPEND = 60;

ALTER WAREHOUSE TALENT_WAREHOUSE
SET MAX_CLUSTER_COUNT = 3;

DROP WAREHOUSE TALENT_WAREHOUSE;

SHOW WAREHOUSES;